### ISSUE TITLE
Roadmap to stable v1.0.0

### ISSUE THREAD

**Issue by WyriHaximus** [reactphp/promise-stream#1]
Proposed roadmap to stable:

## v0.1.0 :white_check_mark: 

* Released 2016-05-10
* Tag current state of this package

## v0.1.1 :white_check_mark: 

* Released 2017-05-15
* Update to support the latest stream tags 

## v0.1.2 :white_check_mark: 

* Released 2017-10-18
* Support maximum buffer size

## v1.0.0 :white_check_mark: 

* Released 2017-10-24
* No new changes, this merely marks the previous release as "stable"

**Comment by WyriHaximus** [comment]
Updated now that [`v0.1.0`](https://github.com/reactphp/promise-stream/releases/tag/v0.1.0) is out.

**Comment by WyriHaximus** [comment]
Updated now that [`v0.1.1`](https://github.com/reactphp/promise-stream/releases/tag/v0.1.1) is out. Next up `v1.0.0` assuming nothing changes in the `stream` and `event-loop` packages and no bugs are found in this package.

**Comment by clue** [comment]
Updated now that [`v1.0.0`](https://github.com/reactphp/promise-stream/releases/tag/v1.0.0) is out :shipit: :tada:
